# Generated by Django 5.0.1 on 2024-01-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_item_id_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='items',
        ),
    ]
