# Generated by Django 5.0.1 on 2024-01-30 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_items_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, editable=False),
        ),
    ]
