# Generated by Django 5.0.1 on 2024-01-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_items_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
