# Generated by Django 5.0.1 on 2024-02-01 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_items_discount_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='slug',
        ),
    ]
