# Generated by Django 5.0.1 on 2024-02-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_items_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='forsell',
            field=models.CharField(default='yes', max_length=100),
            preserve_default=False,
        ),
    ]
