# Generated by Django 5.0.1 on 2024-02-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_items_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quality',
            field=models.IntegerField(default=1),
        ),
    ]
