# Generated by Django 5.0.1 on 2024-02-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='quality',
            field=models.IntegerField(default=2),
        ),
    ]
