# Generated by Django 5.0.1 on 2024-02-23 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_items_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='categories',
            field=models.CharField(choices=[('Ss', 'shirts'), ('S', 'sportshirt'), ('O', 'outwear')], max_length=2),
        ),
    ]
