# Generated by Django 5.0.1 on 2024-02-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_items_label_alter_items_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='categories',
            field=models.CharField(choices=[('T-shirt', 'shirts'), ('Electronics', 'Electronics'), ('SportWear', 'SportWear')], max_length=20),
        ),
    ]
