# Generated by Django 5.0.1 on 2024-02-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_items_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
    ]
