# Generated by Django 5.0.1 on 2024-02-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_items_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quality',
            field=models.IntegerField(default=1),
        ),
    ]
