# Generated by Django 5.0.1 on 2024-02-26 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_items_slug_alter_orderitem_quality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quality',
            new_name='quantity',
        ),
    ]
